### ISSUE TITLE
Feature Request: Toggle Left/Right bound

### ISSUE THREAD

**Issue by d4n3x** [Njanderson/resmon#14]
First I have to thank you for your great extension. I really love to work with it.

In order to have a better overview I would like to bind my resmon to the right side. Due to my other extensions displaying diffferent stuff it looks quiet messy because all is bound to the left side.

At my point of view this would be a great help due to the overview.

greets Danex

**Comment by d4n3x** [comment]
Or maybe being able and change the color of the text (from only this extension) or its background would be awesome - to visually differ between this extension and the others at the first look.

**Comment by d4n3x** [comment]
Already figured it out - starting a pullrequest asap (maybe on monday) :-)

**Comment by Njanderson** [comment]
Thanks! I really appreciate the help. I'll try to get this reviewed quickly for you.

**Comment by eduncan911** [comment]
The PR #15 that was submitted.

**Comment by Njanderson** [comment]
I got this checked in - I'll try to shoot out a release today, and you will see this feature!

Thanks for the feedback!
