### ISSUE TITLE
When laptop is charging shows incorrect battery level

### ISSUE THREAD

**Issue by sjimenez77** [Njanderson/resmon#16]
Curently shows 124% 😆!! 

![image](https://user-images.githubusercontent.com/2870004/64248891-a8ced900-cf12-11e9-84fc-4caa18c7622a.png)

Maybe the solution is something as easy as display 100 when detect a battery level greater.

**Comment by letmaik** [comment]
@Njanderson Maybe updating the `systeminformation` package to the latest version resolves this issue.

**Comment by Njanderson** [comment]
Nice! That's wild! I have not seen that myself. I am updating from minimum systeminformation 3 to 4. Looks like there were some fixes with battery at the end of 2018 - I'm not sure why it displays that! I might put a ceiling at 100%, which is sort of a bandaid.

I'll max it at 100% in the next release (and min it at 0%!).
