### ISSUE TITLE
"resmon.disk.drives" should be of type array?

### ISSUE THREAD

**Issue by acodercc** [Njanderson/resmon#17]
as the title

**Comment by 3rock618** [comment]
Bumping this as I think it needs some explanation:
My drives are named "/dev/root/" , "/dev/loop1/"
![image](https://user-images.githubusercontent.com/26843743/69580781-204c5b80-0f8a-11ea-8bce-426174c1266f.png)
But when I type those into the option
`"resmon.disk.drives" = ["/dev/root/"]`
it returns an empty set.

**Comment by 3rock618** [comment]
Strings array. Has to match the drive name exactly. Took me a but to figure out EXACT match. Example:
"resmon.disk.drives": ["/dev/root", "/dev/loop1"]
![image](https://user-images.githubusercontent.com/26843743/69581319-2b53bb80-0f8b-11ea-8b9e-80da4bd2a160.png)
