### ISSUE TITLE
CPU frequency

### ISSUE THREAD

**Issue by ZenanH** [Njanderson/resmon#20]
- Thank you very much for your work. Resource Monitor is very good. 👍
- I have a problem about CPU frequency:

At present, on my computer, `CPU frequency` shows `Base speed`(①) instead of `speed`(②). The value of `Base speed` will remain unchanged. ![image](https://user-images.githubusercontent.com/19581645/72397985-65b42a80-377c-11ea-958e-4aa8666d43ec.png)

For me, the latter is more important. I'm not sure if this is due to my setting error or if Resource Monitor doesn't support real-time display `speed`.

![批注 2020-01-15 095124](https://user-images.githubusercontent.com/19581645/72398129-e2df9f80-377c-11ea-93ee-7f72ed64be0d.png)

**Comment by letmaik** [comment]
Yes, this should be fixed. Currently resmon uses the [`si.cpu`](https://github.com/sebhildebrandt/systeminformation#3-cpu) API, but instead it should use `si.cpuCurrentspeed`.

**Comment by Njanderson** [comment]
On Windows, this also maxes out your CPU. WMIC (where the systeminformation) doesn't have this information. I have spent a long time trying to figure out a real way to get the current CPU clock speed, but it's very hard to do. On my laptop, which has a max freq. of 2.11 Ghz, every field is listed as this clock speed. I'll do some hunting to see if there is something better on Windows in another node module.

**Comment by Njanderson** [comment]
For example, the NodeJs os.cpus():

```
> os.cpus()
[
  {
    model: 'Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz',
    speed: 2112,
    times: { user: 630312, nice: 0, sys: 494515, idle: 11524515, irq: 77859 }
  },
  {
    model: 'Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz',
    speed: 2112,
    times: { user: 515890, nice: 0, sys: 227203, idle: 11905750, irq: 6234 }
  },
```

**Comment by Njanderson** [comment]
Looking at [other NPM modules](https://github.com/jub3i/node-cpu-stat/blob/master/index.js), they also do this wrong.

**Comment by Njanderson** [comment]
For N=2, my desktop also does this:

```
> cpuCurrentSpeed
Promise {
  { min: 3.6,
    max: 3.6,
    avg: 3.6,
    cores:
     [ 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6 ] },
```

**Comment by Njanderson** [comment]
I've actually invested a ton of time and effort into figuring this out, but I haven't come to a solution that works, not even using C++  and Win32 APIs to measure it in Windows. None of the example programs actually match Task Manager, and I cannot comment on what Task Manager does.

**Comment by letmaik** [comment]
Ah that's a shame, I had no idea the situation was so dire. I think for now then this should be documented, also in the description text of the vs code setting. You can Markdown now, so could even apply some formatting etc.

**Comment by Njanderson** [comment]
For Intel processors, you can do something like [this extension](https://github.com/openhardwaremonitor/openhardwaremonitor/blob/5b34d265b625c47a0612fdf606cbaa71b0dab12c/Hardware/CPU/IntelCPU.cs) does, which is read an Intel CPU MSR, which gives the current CPU operating point.

**Comment by Njanderson** [comment]
Agreed - I actually think this works okay in Linux.

If someone can comment on whether cpuCurrentspeed (Yes, the capitalization in systeminformation is not quite camel-cased) is required for Linux, I'd appreciate it!

**Comment by Njanderson** [comment]
Taking an action item to document this for Windows, and leave Linux/MacOS as is.

**Comment by Njanderson** [comment]
For @ZenanH, I'm sorry I couldn't help more on this.

**Comment by letmaik** [comment]
I think we want cpuCurrentspeed, as si.cpu just parses the "Model name:" line of `lscpu` and doesn't query the current speed, except as fall-back if the number is 0. I'm personally never interested in the static/base cpu speed.

**Comment by Njanderson** [comment]
Moving onto cpuCurrentspeed.
