### ISSUE TITLE
Show "N/A" if no battery available

### ISSUE THREAD

**Issue by letmaik** [Njanderson/resmon#24]
Currently, if the system has no battery, then "0%" is shown. [systeminformation](https://github.com/sebhildebrandt/systeminformation#5-battery) has `si.hasbattery` which should be queried to check whether a battery is available, and if not, show "N/A". Automatic hiding of the battery indicator would probably be even more useful.

**Comment by Njanderson** [comment]
Moving to not displaying it instead if no battery is detected.
