### ISSUE TITLE
How can I use this extension?

### ISSUE THREAD

**Issue by TimJeskeSensape** [Njanderson/resmon#3]
I installed the extension in vscode, but I don't know how I can use it.

**Comment by Njanderson** [comment]
Sorry about this - I thought I fixed this with 1.0.1, but I'm not sure what I pushed. Thanks to another community member for noticing that I did not do this.

**Comment by Njanderson** [comment]
Let me know if updating does not solve your problem.

**Comment by lgaitan** [comment]
I've updated and it is now working
