### ISSUE TITLE
Allow option to show *active* memory instead of *used*

### ISSUE THREAD

**Issue by hcaw** [Njanderson/resmon#4]
When using the extension, it will show how much memory is being "used", which in the `systeminformation` module [includes buffers & cache](https://www.npmjs.com/package/systeminformation#3-cpu-memory-disks-battery-graphics). This figure can be misleading, as buffered and cached memory is [still technically available for use if needed](https://www.linuxatemyram.com/).
I propose that either the *used* figure should default to a figure which does not include buffers and cache (referred to as `active` by the `systeminformation` module), or to allow the user an option in the configuration settings to change between the two (including or excluding buffers & cache).

**Comment by Njanderson** [comment]
I'm taking a look at this. Thanks for your feedback!

**Comment by Njanderson** [comment]
Thanks - I should have addressed this now.

Let me know if there are any more requests that you may have. I was thinking of having a graph over time of the data, sort of like the Ubuntu System Monitor.

What do you think?
