### ISSUE TITLE
Feature Request: Disk Space

### ISSUE THREAD

**Issue by 3rock618** [Njanderson/resmon#5]
Hi, I love this extension. I am using it with the new MS Remote SSH feature, it adds a lot of value and convenience to my dev experience. 

I use a barebones linux aws ec2, and I try to monitor disk space which helps keep cost down. It would be amazing to have an option to monitor disk space, so I can see if I'm running out of room. Perhaps just a single number in Gb for available disk space would be amazing. 

Thank you for your work 🙏🏼

**Comment by Njanderson** [comment]
I'm on it! I'll start on this tonight.

**Comment by Njanderson** [comment]
Hey! I finally merged something in and published this change in 1.0.6.

Let me know if that works for you! You should be able to filter based on individual disks or just show all of them.

**Comment by Njanderson** [comment]
Please re-open if this is still an issue or if there is an enhancement that I should add.

**Comment by fakhamatia** [comment]
How set disks in setting ? How set on Linux and windows `"resmon.disk.drives": []` ?
Please update "Extension Settings" in extension page

**Comment by 3rock618** [comment]
My preference for this feature would be to follow the convention of the other monitors - the display shows just the icon and the number.

`🀚 1.4 Gb`

You could also have an additional setting for displaying the disk name something like `"resmon.show.disk.name" = true`
`🀚 1.4 Gb /dev/nvme0n1p1`

As you can see AWS does not use human friendly disk names, so having that display doesn't really add any value in my case.

I understand the impulse to add the word "used" or "remaining" to reduce confusion,but technically you have the same exactly problem with the memory monitor, and we all seem to figure it out. If it's important you could have another setting.
`"resmon.show.disk.descriptor" = true`
`🀚 1.4 Gb remaining` or `🀚 1.4/9.8 Gb used`

The main reason for this comment is that the status bar real estate is an important resource, so having things displayed efficiently is critical to my workflow. I'd rather have efficient use of space than 100% clarity. I can be 95% clear if the design is clean and and efficient. MHO.

**Comment by fakhamatia** [comment]
> "resmon.show.disk.name" = true

Is "Unknown configuration setting"

When set ""resmon.show.disk": true," , all systems monitoring disappear

**Comment by 3rock618** [comment]
That's because `"resmon.show.disk.name"` is not a real thing. I was suggesting it as an additional feature.

The main point of the above post was that contrary to all the other monitors this one seemed a little cluttered, so I was making some suggestions to the author as to how to declutter it, while making an additional suggestion as to how to keep some of the functionality as an option.

**Comment by 3rock618** [comment]
Got this figured out. Thank you
https://github.com/Njanderson/resmon/issues/17#issuecomment-558357441
