### ISSUE TITLE
Feature Request: Temperature

### ISSUE THREAD

**Issue by fakhamatia** [Njanderson/resmon#7]
Please add option to show Temperature 

Thank you

**Comment by Njanderson** [comment]
Hey! I have added this. The dependency that I am using seems suspect (on my machine, it's returning -1 C, so I might need to go back to the drawing board).

I have some other ways I can look into doing this. I'd be curious to know if this works for you as is. 

Could you re-open with feedback after you try revision 1.0.6?

**Comment by fakhamatia** [comment]
I update extension, its Show The Temperature of CPU OK in Ubuntu 18.04.
Witch core its show? can set option to chose temp of cpu or mainboard?

**Comment by fakhamatia** [comment]
> on my machine, it's returning -1 C

In windows 10 show -1
