### ISSUE TITLE
Feature Request: Only show when use remote 

### ISSUE THREAD

**Issue by fakhamatia** [Njanderson/resmon#8]
Please add option to only show system monitor when use remote extensions

**Comment by 3rock618** [comment]
@fakhamatia why did you close this? Did you find an alternative solution?

**Comment by fakhamatia** [comment]
> @fakhamatia why did you close this? Did you find an alternative solution?
> 
> I agree it would be cool to have two profiles - local vs remote.
I thought I was not interesting at first, so I closed it

**Comment by Njanderson** [comment]
I can look into adding this. I am a little busy this week, but I can try to squeeze starting researching what I'd like to do here!

Thanks for the feedback!

**Comment by 3rock618** [comment]
I actually did find a relatively good solution for this. You can store you global resmon settings in your global settings on your local machine (found by hitting ctrl/cmd + comma).

For reference, on my mac the folder is:
`/Users/erik/Library/Application Support/Code - Insiders/User/settings.json`

Then, you can have your remote resmon settings on your remote machine. The remote settings will override the global ones:
- In the remote folder or workspace you use in your remote env there should be a folder called `/.vscode`, if not create it
- in that folder there may be a `settings.json`, if not create
- store your local resmon settings in there.

In my project the path is:
`/home/ubuntu/project/.vscode/settings.json`

**Comment by letmaik** [comment]
I think this is a non-issue.
As for @fakhamatia's original request, you can already do that by simply not installing the extension locally but instead only on the remote. VS Code supports that.
Having different settings per remote or locally (@3rock618's use case) is also supported natively by VS Code by using the different configuration files or VS Code's configuration UI.
Everyone happy closing this?

**Comment by Njanderson** [comment]
Looks like we are okay with leaving this issue as is.

**Comment by alexkuc** [comment]
If someone knows to achieve "disable locally, enable remotely", please share how to do that. After checking VSCode docs and Google I didn't find a straight forward way to do that.

Edit: never mind, found it [here](https://code.visualstudio.com/docs/remote/ssh#_advanced-forcing-an-extension-to-run-locally-remotely)
